name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: deploy env
        options: 
          - stg
          - prd
      mode:
        type: choice
        description: yarn mode
        options: 
          - development
          - production
jobs:
  get-sha:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7
  call-build:
    needs: get-sha
    uses: spazious/github-actions-workflows/.github/workflows/front-build.yaml@master
    with:
      environment: ${{ inputs.environment }}
      tag:  ${{ needs.get-sha.outputs.short-sha }}
      project_name: ${{ github.event.repository.name }}
      mode: ${{ inputs.mode }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PRITUNL_PROFILE_FILE: ${{ secrets.PRITUNL_PROFILE_FILE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}