name: GCP Build
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      project_name:
        required: true
        type: string
      mode:
        description: 'yarn mode parameter'
        required: true
        default: 'development'
        type: string
      environment:
        description: 'environment where the service will be deployed'
        required: true
        default: 'stg'
        type: string
      dockerfile:
        required: false
        type: string
        default: "Dockerfile"
      no-cache:
        required: false
        type: string
        default: "false"
    secrets:
      GOOGLE_CREDENTIALS:
        required: false
      GCR_REGISTRY:
        required: false
      GH_PAT:
        required: true
      VAULT_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      PRITUNL_PROFILE_FILE:
        required: true
      SPZ_HISTORY_WIF:
        required: false
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Pritunl Profile and Start VPN Connection
          id: pritunl-connection
          uses: nathanielvarona/pritunl-client-github-action@v1.1.3
          with:
            profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
                
        - name: Get Global Secrets
          id: global-secrets
          uses: bjerkio/vault-action@v1.0.2
          with:
            endpoint: "https://vault.services.spazious.com"
            path: "ci/global"
            authMethod: token
            token: ${{ secrets.VAULT_TOKEN }}
      
        # - uses: healthplace/npmrc-registry-login-action@v1.0
        #   with:
        #     scope: '@spazious'
        #     registry: "https://nexus.services.spazious.com/repository/spazious-npm/"
        #     auth-token: ''
  
        # - uses: mskelton/setup-yarn@v1
        #   env:
        #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        #   with:
        #     node-version: '18.x'

        # - name: Securirity Scan
        #   env:
        #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        #   continue-on-error: true
        #   run: yarn audit

        - name: Setup Vault Cli
          uses: eLco/setup-vault@v1
          with:
             version: '~1.9.2'
          
        - name: Create .env
          env:
            VAULT_ADDR: "https://vault.services.spazious.com"
            VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          run: |
            vault kv get -format yaml -field=data "ci/${{ inputs.project_name }}/${{ inputs.environment }}"| sed 's/: /=/' > .env
      
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: gcr.io
            username: _json_key
            password: ${{ secrets.GOOGLE_CREDENTIALS }}
  
        - name: Build and push the tagged docker image to Amazon ECR
          env:
            TARGET: ${{ inputs.mode }}
            ENVIRONMENT: ${{ inputs.environment}}
          run: |
              args=()
              while IFS='=' read -r key value; do
                args+=(--build-arg "$key=$value")
              done < .env
              DOCKER_BUILDKIT=1 docker build -f ${{ inputs.dockerfile }} "${args[@]}" --build-arg SRC=$TARGET -t gcr.io/prj-management-407914/${{ inputs.project_name }}:${{ inputs.tag }} .
              docker push gcr.io/prj-management-407914/${{ inputs.project_name }}:${{ inputs.tag }}
