name: Promote
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: deploy env
        options: 
          - v3 
          - stg
          - prd
      version:
        type: string
        description: commitd_id or tag to be deployed
jobs:
  call-promote:
    uses: spazious/github-actions-workflows/.github/workflows/promote.yaml@master
    with:
      env: ${{ inputs.environment }}
      tag:  ${{ inputs.version }}
      project_name: ${{ github.event.repository.name }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
