name: promote

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      env:
        required: true
        type: string
      project_name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      ARGOCD_TOKEN:
        required: false
      
jobs:
  check-envs:
    runs-on: ubuntu-22.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Checkout Helm Specs
        uses: actions/checkout@v3
        with:
          repository: spazious/helm-specs
          token: ${{ secrets.GH_PAT }} 
          path: source

      - name: Write inplace tag
        id: lookupSdkVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.image.tag = "${{ inputs.tag }}"' source/${{ inputs.project_name }}/${{ inputs.env }}/specs.yaml

      - name: Push file
        id: push
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source_file: source/${{ inputs.project_name }}/${{ inputs.env }}/specs.yaml
          destination_repo: 'spazious/helm-specs'
          destination_folder: '${{ inputs.project_name }}/${{ inputs.env }}/'
          destination_branch: master
          user_email: '${{ github.event.repository.name }}@spazious.rocks'
          user_name: '${{ github.event.repository.name }}'
          commit_message: 'deployment from ${{ github.event.repository.name }}'

      - name: Retry on failure
        if: steps.push.outcome == 'failure'
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: source/${{ inputs.project_name }}/${{ inputs.env }}/specs.yaml
          destination_repo: 'spazious/helm-specs/${{ inputs.project_name }}/${{ inputs.env }}/specs.yaml'
          destination_folder: '${{ inputs.project_name }}/${{ inputs.env }}/'
          destination_branch: master
          user_email: '${{ github.event.repository.name }}@spazious.rocks'
          user_name: '${{ github.event.repository.name }}'
          commit_message: 'deployment from ${{ github.event.repository.name }}'

